### ISSUE TITLE
Data loading race condition / state label z-index issue

### ISSUE THREAD

**Issue by bscofield** [DevProgress/maps-showcase#111]
When digging into https://github.com/DevProgress/maps-showcase/issues/92, we discovered that:

1) there's a race condition when loading the state data -- it's sometimes unavailable when the tooltip (state labels) are loaded. That doesn't stop the modal from appearing, but
2) on those occasions when the state data is loaded in time for the tooltips to load, the first tap on a state shows the label, then the second opens the modal -- but the tooltip stays visible, on top of the modal. 

This may be primarily a development-side issue (due to differences in how quickly the data can be served up on a laptop vs. on a production server), but it might be worth a little robustification regardless.

**Comment by jillh510** [comment]
Is this a priority to fix, or should it go to "wontfix" land?

**Comment by bscofield** [comment]
I'd lean towards `wontfix`, just because it's so much less likely in production.

**Comment by jillh510** [comment]
wontfix it is; reopen if it becomes a problem in production or a real nuisance to developers.
