### ISSUE TITLE
Add text labels/links for small states

### ISSUE THREAD

**Issue by brianlevy** [DevProgress/maps-showcase#38]
States like Maryland, Delaware, Connecticut and Rhode Island have very small click/touch targets. Additionally the combination of smaller size and close proximity of east coast states adds more cognitive effort to clicking the intended state. Adding text labels/links would improve the usability.

**Comment by andrewljohnson** [comment]
We're basing the design off the provided mocks, not sure if we should start improving those without direction.

**Comment by andrewljohnson** [comment]
Actually now that I look, some small states do have lines jutting out with labels in the mocks :)

**Comment by kahneraja** [comment]
Given we have zoom perhaps this is not required?

**Comment by decause** [comment]
Done!
