### ISSUE TITLE
Make modal next button support multiple slides

### ISSUE THREAD

**Issue by dxa4481** [DevProgress/maps-showcase#51]
Currently next and previous buttons just take you to the next state. The states should support more than one slide.

**Comment by andrewjtimmons** [comment]
Is there already slides data on there?  I looked through the folders and couldn't find the data that should be scrolled through.

**Comment by dxa4481** [comment]
We don't have any slide data yet, but I have it on good authority states should support more than one slide

**Comment by andrewjtimmons** [comment]
Totally.  I think this is a good goal.  Just wondering if we know what the data structure/directory structure of the slides will look like so we can start scaffolding it. :)

**Comment by dxa4481** [comment]
So for that, I think we're going with separate folders for each state

stateFolder1 -> Slides
stateFolder2-> Slides
etc...

**Comment by andrewljohnson** [comment]
FWIW if the slides were indexed into the JSON, the file structure could be
flat.

**Comment by kahneraja** [comment]
This has been addressed with a json file :)
