### ISSUE TITLE
Use Unity Sharp typeface in each site

### ISSUE THREAD

**Issue by decause** [DevProgress/maps-showcase#58]
https://a.hrc.onl/secretary/fonts/SharpUnity-Extrabold.ttf

![screenshot from 2016-08-22 17-00-25](https://cloud.githubusercontent.com/assets/427420/17871548/0ccdeee8-688a-11e6-9ab8-7b3ec0041100.png)

**Comment by andrewljohnson** [comment]
I'm using this, but I noticed the text in the bottom section ends up bolder than the mock.

Is there a non-bold version of this font we should have too?

**Comment by dxa4481** [comment]
Ahh @andrewljohnson I just commented on the PR, try adjusting the font-weight attribute for the modal. That should hopefully make it look more like the mock

**Comment by andrewljohnson** [comment]
I tried adjusting the font-weight, but wasn't having any luck. I thought it
might be because the font started out extra bold style.

 I'll try again later.

**Comment by brianlevy** [comment]
The font @decause supplied is only the extra bold weight. I've asked about getting the other weights.

**Comment by kahneraja** [comment]
Fonts added to maps app. Are we done here?
